In [71]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy.stats import norm
from warnings import filterwarnings
filterwarnings('ignore')
from delta_hedging import delta_hedging

In [28]:
def bs_call(s0, k, rf, q, sigma, tau):
    '''PutCall for 'c', 'p' '''
    d1 = (np.log(s0/k) +((rf - q +0.5*np.power(sigma, 2))*tau))/(sigma*np.sqrt(tau))
    d2 = d1 - sigma*np.sqrt(tau)
    value = s0*norm.cdf(d1) - k*np.exp(-rf*tau)*norm.cdf(d2)

    return value

def stock_path(mu, q, sigma, dt, T, simul=10000):

    value = np.ones((2, simul)) * s0

    for idx in range(1, T + 1):
        d_term = (mu - q - 0.5 * sigma**2) * dt
        s_term = sigma * np.sqrt(dt) * np.random.normal(size=(simul))

        value = np.vstack([value, value[-1] * np.exp(d_term + s_term)])
        
    value = value[1:]

    return value


In [40]:
''' T는 전체 기간, dt는 time step, tau 는 T x dt '''
s0 = 50000; k = 55000; q=0; rf = 0.04; sigma=0.4; T=130; dt=1/260; tau=T*dt
bs_call(s0, k, rf, q, sigma, tau)

4092.0174385438695

In [45]:
mu=0.04; q=0
path = stock_path(mu, q, sigma, dt, T, simul=10000)

## IV change

In [ ]:
['sigma=40%', 'sigma=34%', 'sigma=46%']

In [69]:
sigma1 = 0.34; sigma2 = 0.46
ori_call_value = bs_call(s0, k, rf, q, sigma, tau)
over_call_value = bs_call(s0, k, rf, q, sigma1, tau)
under_call_value = bs_call(s0, k, rf, q, sigma2, tau)

call_value_table = pd.DataFrame(data=[ori_call_value, over_call_value, under_call_value], index=['sigma=40%', 'sigma=34%', 'sigma=46%']).T
call_value_table

sigma=40%    sigma=34%    sigma=46%
0  4092.017439  3256.344523  4934.297619

In [70]:
pat

array([[50000.        , 50000.        , 50000.        , ...,
        50000.        , 50000.        , 50000.        ],
       [48350.61618489, 50359.980957  , 50445.24212806, ...,
        48683.54190527, 48883.94287887, 50033.71230235],
       [47455.76810695, 50170.49236866, 51878.62778788, ...,
        45889.31418564, 48530.0145482 , 50137.62995551],
       ...,
       [52646.79019726, 39641.67388136, 35748.82997789, ...,
        45175.49239506, 37520.02648062, 22953.01327269],
       [52029.77521638, 40760.15975332, 36243.56335801, ...,
        46779.24030015, 38688.61635202, 23345.2604761 ],
       [52811.01999557, 40588.19964387, 36975.11698505, ...,
        47033.99645451, 38032.67734898, 22372.40444544]])

In [76]:
inputs = {
    's0' : 50000,
    'k' : 55000,
    'rf' : 0.04,
    'sigma' : 0.4,
    'imvol' : 0.4,
    'T' : 1,
    'mu' : 0.04,
    'q' : 0,
    'interval' : 1/260,
    'time_step' : 130,
    'simul_num' : 10000,
    'num_shares' : 100000
}
dh = delta_hedging(inputs)

In [81]:
dh.bs_call('c')

4092.0174385438695

In [141]:
tmp

array([4.50324976e-01, 3.92541878e-01, 3.79393515e-01, 4.00175118e-01,
       3.97134235e-01, 4.24622324e-01, 3.85053972e-01, 3.51248508e-01,
       4.21256122e-01, 4.02488845e-01, 3.79505609e-01, 4.40653092e-01,
       4.14678016e-01, 3.77284295e-01, 3.87922254e-01, 3.91220039e-01,
       4.15297074e-01, 4.25862505e-01, 4.24827866e-01, 3.98701721e-01,
       4.06362207e-01, 3.91022631e-01, 3.76631393e-01, 4.09631324e-01,
       4.93654234e-01, 5.01730583e-01, 4.29736139e-01, 4.51592574e-01,
       3.91642599e-01, 3.57257630e-01, 3.76332825e-01, 3.97158465e-01,
       2.94287576e-01, 2.87636026e-01, 2.58614498e-01, 2.11579129e-01,
       2.03361895e-01, 1.92412070e-01, 2.03706489e-01, 1.52433094e-01,
       1.10083910e-01, 1.06955956e-01, 9.68282864e-02, 9.06383125e-02,
       9.33715046e-02, 1.15601514e-01, 1.36596971e-01, 1.68354838e-01,
       1.40954398e-01, 1.22084422e-01, 1.29367188e-01, 1.68567044e-01,
       1.64979721e-01, 1.27029281e-01, 1.59840854e-01, 1.37280172e-01,
      

In [144]:
stock_prices.values * delta_path.values

array([[2.25162488e+04],
       [1.88374831e+04],
       [1.80454214e+04],
       [1.93398114e+04],
       [1.91649788e+04],
       [2.09129040e+04],
       [1.84488947e+04],
       [1.64318107e+04],
       [2.07401676e+04],
       [1.95704965e+04],
       [1.81686288e+04],
       [2.20322376e+04],
       [2.03797139e+04],
       [1.80779304e+04],
       [1.87420235e+04],
       [1.89596090e+04],
       [2.04767759e+04],
       [2.11629090e+04],
       [2.11112208e+04],
       [1.94815510e+04],
       [1.99736558e+04],
       [1.90369964e+04],
       [1.81734445e+04],
       [2.02229533e+04],
       [2.57498148e+04],
       [2.63187692e+04],
       [2.15410370e+04],
       [2.29701536e+04],
       [1.91814301e+04],
       [1.71195932e+04],
       [1.82784859e+04],
       [1.95675229e+04],
       [1.35457372e+04],
       [1.31920057e+04],
       [1.16254797e+04],
       [9.17671754e+03],
       [8.77260604e+03],
       [8.23500176e+03],
       [8.81693332e+03],
       [6.30595869e+03],


In [161]:
df = pd.DataFrame()

'''주가 생성'''
path = dh.stock_path()
stock_prices = pd.DataFrame(path[:,0], columns=['S'])

'''델타 생성'''
tmp = dh.path_delta(path)[:,0]
delta_path = pd.DataFrame(tmp, columns=['Delta'])

'''사야되는 델타 값'''
delta_shares = dh.path_changes(dh.path_delta_shares(path))[:,0]
delta_shares = pd.DataFrame(delta_shares, columns=['#Buy_ch'])

'''Cost'''
cost = dh.path_changes(dh.path_delta_shares_cost(path))[:,0]
cost = pd.DataFrame(cost, columns=['#Cost_ch'])

'''Cum Cost'''
cum_cost = dh.path_delta_hedged_cum(path)[:,0]
cum_cost = pd.DataFrame(cum_cost, columns=['#Cum_Cost'])

'''Int Cost'''
int_cost = dh.delta_hedging_int_cost(path)[:,0]
int_cost = pd.DataFrame(int_cost, columns=['Int_Cost'])

'''합치기'''
df = pd.concat([df, stock_prices, delta_path, delta_shares, cost, cum_cost], axis=1)
np.round(df,1)

S  Delta  #Buy_ch      #Cost_ch     #Cum_Cost
0     50000.0    0.5  45032.5  2.251625e+09  2.251625e+09
1     50188.7    0.5    445.4  3.085123e+07  2.284208e+09
2     49527.4    0.4  -1949.6 -1.266335e+08  2.159332e+09
3     51269.4    0.5   4813.4  3.226057e+08  2.483598e+09
4     49233.8    0.4  -5832.9 -3.855762e+08  2.099933e+09
..        ...    ...      ...           ...           ...
126   97274.6    1.0      0.0  2.130292e+08  1.021735e+10
127   97527.1    1.0      0.0  2.524183e+07  1.025046e+10
128   97735.7    1.0      0.0  2.086953e+07  1.027921e+10
129   98387.9    1.0      0.0  6.521958e+07  1.035234e+10
130  101439.3    1.0      0.0  3.051406e+08  1.066544e+10

[131 rows x 5 columns]

In [117]:
df['S'] * df['#Delta']

0      22516.248803
1      21193.040719
2      20440.499580
3      23445.191287
4      23104.539777
           ...     
126    52620.980942
127    61448.981082
128    59808.652329
129    56068.741134
130    58456.175703
Length: 131, dtype: float64

In [22]:
s0 = 49; k = 50; q=0; rf = 0.05; sigma=0.2; tau=100/260
bs_call(s0, k, rf, q, sigma, tau)

2.4005273232717137

In [9]:
'''Parameters'''
inputs = {
    's0' : 50000,
    'k' : 55000,
    'rf' : 0.04,
    'sigma' : 0.4,
    'imvol' : 0.,
    'T' : 1,
    'mu' : 0,
    'q' : 0,
    'interval' : 'Daily',
    'time_step' : 20,
    'simul_num' : 10000,
    'num_shares' : 100000
}

In [10]:
dh = delta_hedging(inputs)

In [11]:
dh.bs_call('c')

4.945099847804315